version: "3.8"

services:
  # Container MySQL
  mysql-db:
    image: mysql:8.0
    container_name: rbac-mysql
    restart: always
    environment:
      MYSQL_DATABASE: learnmanagement
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "3306:3306"
    volumes:
      # - ./docker-config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  # Container Redis
  redis-cache:
    image: redis:alpine
    container_name: rbac-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
