version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: rbac-mysql
    restart: always
    environment:
      MYSQL_DATABASE: learnmangement
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    container_name: rbac-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
